#!/usr/bin/env bash

reinstall_workbench() {
    bash <(curl -s https://raw.githubusercontent.com/randy3k/workbench/master/install.sh)
}

uninstall_workbench() {
    rm -rf ~/.local/workbench
    rm ~/.local/bin/workbench
}


case "$1" in
    run)
        shift
        [ -z "$1" ] && echo "missing argument" && exit 1
        SCRIPT="$1"
        shift
        bash ~/.local/workbench/script/$SCRIPT.sh
    ;;
    list)
        cd ~/.local/workbench/script
        SCRIPTS=$(find . -type f | sed 's;\./\(.*\)\.sh;\1;')
        echo "$SCRIPTS" | grep --color=never '/'
        echo "$SCRIPTS" | grep -v --color=never '/'
    ;;
    cat)
        shift
        [ -z "$1" ] && echo "missing argument" && exit 1
        SCRIPT="$1"
        shift
        cat ~/.local/workbench/script/$SCRIPT.sh
    ;;
    reinstall)
        reinstall_workbench
    ;;
    uninstall)
        uninstall_workbench
    ;;
    *)
        echo "Usage: workbench [list|run|cat|reinstall|uninstall]"
    ;;
esac
