#!/usr/bin/env bash

reinstall_workbench() {
    bash <(curl -s https://raw.githubusercontent.com/randy3k/workbench/master/install.sh)
}

uninstall_workbench() {
    rm -rf ~/.local/workbench
    rm ~/.local/bin/workbench
}


case "$1" in
    run)
        shift
        [ -z "$1" ] && echo "missing argument" && exit 1
        FILE="$1"
        shift
        bash ~/.local/$NAME/run/$FILE.sh
    ;;
    list)
        cd ~/.local/$NAME/run
        ls -C1 *.sh | sed 's/\(.*\).sh/\1/'
    ;;
    reinstall)
        reinstall_workbench
    ;;
    uninstall)
        uninstall_workbench
    ;;
    *)
        echo "Usage: workbench [list|run|sshkey|reinstall|uninstall]"
    ;;
esac
